"""add oauth tables

Revision ID: fbc51d6de763
Revises: 017_user_language
Create Date: 2026-03-02 16:12:07.820713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbc51d6de763'
down_revision: Union[str, None] = '017_user_language'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('oauth_clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('client_name', sa.String(length=100), nullable=False),
    sa.Column('redirect_uris', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_clients_client_id', 'oauth_clients', ['client_id'], unique=False)
    op.create_index(op.f('ix_oauth_clients_client_id'), 'oauth_clients', ['client_id'], unique=True)
    op.create_index(op.f('ix_oauth_clients_id'), 'oauth_clients', ['id'], unique=False)
    op.create_table('oauth_access_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('access_token', sa.String(length=256), nullable=False),
    sa.Column('refresh_token', sa.String(length=256), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('refresh_token_expires_at', sa.String(), nullable=True),
    sa.Column('revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_tokens_access', 'oauth_access_tokens', ['access_token'], unique=False)
    op.create_index('idx_oauth_tokens_refresh', 'oauth_access_tokens', ['refresh_token'], unique=False)
    op.create_index('idx_oauth_tokens_user', 'oauth_access_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_access_token'), 'oauth_access_tokens', ['access_token'], unique=True)
    op.create_index(op.f('ix_oauth_access_tokens_id'), 'oauth_access_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_oauth_access_tokens_refresh_token'), 'oauth_access_tokens', ['refresh_token'], unique=True)
    op.create_table('oauth_authorization_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=128), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_challenge', sa.String(length=128), nullable=False),
    sa.Column('code_challenge_method', sa.String(length=10), nullable=False),
    sa.Column('redirect_uri', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['oauth_clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_oauth_codes_client', 'oauth_authorization_codes', ['client_id'], unique=False)
    op.create_index('idx_oauth_codes_code', 'oauth_authorization_codes', ['code'], unique=False)
    op.create_index(op.f('ix_oauth_authorization_codes_code'), 'oauth_authorization_codes', ['code'], unique=True)
    op.create_index(op.f('ix_oauth_authorization_codes_id'), 'oauth_authorization_codes', ['id'], unique=False)
    op.alter_column('body_measurement_entries', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_body_measurement_entries_id'), 'body_measurement_entries', ['id'], unique=False)
    op.create_index(op.f('ix_budget_settings_id'), 'budget_settings', ['id'], unique=False)
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    op.create_index(op.f('ix_exercise_sets_id'), 'exercise_sets', ['id'], unique=False)
    op.create_index('idx_exercises_workout', 'exercises', ['workout_id'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index('idx_food_categories_name', 'food_categories', ['name'], unique=False)
    op.create_index(op.f('ix_food_categories_id'), 'food_categories', ['id'], unique=False)
    op.create_index('idx_food_consumption_log_consumed_at', 'food_consumption_log', ['consumed_at'], unique=False)
    op.create_index('idx_food_consumption_log_user', 'food_consumption_log', ['user_id'], unique=False)
    op.create_index(op.f('ix_food_consumption_log_id'), 'food_consumption_log', ['id'], unique=False)
    op.create_index('idx_food_expiry_reminders_inventory', 'food_expiry_reminders', ['inventory_item_id'], unique=False)
    op.create_index('idx_food_expiry_reminders_status', 'food_expiry_reminders', ['status'], unique=False)
    op.create_index('idx_food_expiry_reminders_user', 'food_expiry_reminders', ['user_id'], unique=False)
    op.create_index(op.f('ix_food_expiry_reminders_id'), 'food_expiry_reminders', ['id'], unique=False)
    op.create_index('idx_food_inventory_expiry', 'food_inventory', ['expiry_date'], unique=False)
    op.create_index('idx_food_inventory_household', 'food_inventory', ['household_id'], unique=False)
    op.create_index('idx_food_inventory_location', 'food_inventory', ['location'], unique=False)
    op.create_index('idx_food_inventory_product', 'food_inventory', ['product_id'], unique=False)
    op.create_index('idx_food_inventory_status', 'food_inventory', ['status'], unique=False)
    op.create_index('idx_food_inventory_user', 'food_inventory', ['user_id'], unique=False)
    op.create_index(op.f('ix_food_inventory_id'), 'food_inventory', ['id'], unique=False)
    op.create_index('idx_food_pending_import_items_import', 'food_pending_import_items', ['pending_import_id'], unique=False)
    op.create_index('idx_food_pending_import_items_status', 'food_pending_import_items', ['status'], unique=False)
    op.create_index(op.f('ix_food_pending_import_items_id'), 'food_pending_import_items', ['id'], unique=False)
    op.create_index('idx_food_pending_imports_household', 'food_pending_imports', ['household_id'], unique=False)
    op.create_index('idx_food_pending_imports_receipt', 'food_pending_imports', ['receipt_id'], unique=False)
    op.create_index('idx_food_pending_imports_status', 'food_pending_imports', ['status'], unique=False)
    op.create_index('idx_food_pending_imports_user', 'food_pending_imports', ['user_id'], unique=False)
    op.create_index(op.f('ix_food_pending_imports_id'), 'food_pending_imports', ['id'], unique=False)
    op.create_index('idx_food_product_aliases_normalized', 'food_product_aliases', ['alias_normalized'], unique=False)
    op.create_index('idx_food_product_aliases_product', 'food_product_aliases', ['product_id'], unique=False)
    op.create_index(op.f('ix_food_product_aliases_id'), 'food_product_aliases', ['id'], unique=False)
    op.create_index('idx_food_products_barcode', 'food_products', ['barcode'], unique=False)
    op.create_index('idx_food_products_category', 'food_products', ['food_category_id'], unique=False)
    op.create_index('idx_food_products_name_normalized', 'food_products', ['name_normalized'], unique=False)
    op.create_index(op.f('ix_food_products_id'), 'food_products', ['id'], unique=False)
    op.create_index(op.f('ix_food_reminder_settings_id'), 'food_reminder_settings', ['id'], unique=False)
    op.create_index('idx_household_budget_settings_budget', 'household_budget_settings', ['budget_settings_id'], unique=False)
    op.create_index('idx_household_budget_settings_household', 'household_budget_settings', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_budget_settings_id'), 'household_budget_settings', ['id'], unique=False)
    op.create_index('idx_household_categories_category', 'household_categories', ['category_id'], unique=False)
    op.create_index('idx_household_categories_household', 'household_categories', ['household_id'], unique=False)
    op.create_index(op.f('ix_household_categories_id'), 'household_categories', ['id'], unique=False)
    op.create_index('idx_household_invitations_household', 'household_invitations', ['household_id'], unique=False)
    op.create_index('idx_household_invitations_token', 'household_invitations', ['token'], unique=False)
    op.create_index(op.f('ix_household_invitations_id'), 'household_invitations', ['id'], unique=False)
    op.create_index('idx_household_members_household', 'household_members', ['household_id'], unique=False)
    op.create_index('idx_household_members_user', 'household_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_household_members_id'), 'household_members', ['id'], unique=False)
    op.create_index('idx_household_receipts_household', 'household_receipts', ['household_id'], unique=False)
    op.create_index('idx_household_receipts_receipt', 'household_receipts', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_household_receipts_id'), 'household_receipts', ['id'], unique=False)
    op.create_index('idx_household_transactions_household', 'household_transactions', ['household_id'], unique=False)
    op.create_index('idx_household_transactions_transaction', 'household_transactions', ['transaction_id'], unique=False)
    op.create_index(op.f('ix_household_transactions_id'), 'household_transactions', ['id'], unique=False)
    op.create_index('idx_households_uid', 'households', ['uid'], unique=False)
    op.create_index(op.f('ix_households_id'), 'households', ['id'], unique=False)
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_journal_entries_date'), 'journal_entries', ['date'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_items_id'), 'journal_items', ['id'], unique=False)
    op.alter_column('journal_reports', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_journal_reports_id'), 'journal_reports', ['id'], unique=False)
    op.alter_column('medicine_logs', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_medicine_logs_id'), 'medicine_logs', ['id'], unique=False)
    op.alter_column('medicine_schedules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_medicine_schedules_id'), 'medicine_schedules', ['id'], unique=False)
    op.alter_column('medicines', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_medicines_id'), 'medicines', ['id'], unique=False)
    op.alter_column('meditation_sessions', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('meditation_sessions', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_meditation_sessions_id'), 'meditation_sessions', ['id'], unique=False)
    op.create_index('idx_monthly_imports_month', 'monthly_imports', ['month'], unique=False)
    op.create_index(op.f('ix_monthly_imports_id'), 'monthly_imports', ['id'], unique=False)
    op.alter_column('notification_schedules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index('idx_receipts_category', 'receipts', ['category'], unique=False)
    op.create_index('idx_receipts_merchant', 'receipts', ['merchant'], unique=False)
    op.create_index('idx_receipts_scan_date', 'receipts', ['scan_date'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_shopping_list_items_id'), 'shopping_list_items', ['id'], unique=False)
    op.alter_column('shopping_lists', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_shopping_lists_id'), 'shopping_lists', ['id'], unique=False)
    op.alter_column('todo_items', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_todo_items_id'), 'todo_items', ['id'], unique=False)
    op.alter_column('todo_lists', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_todo_lists_id'), 'todo_lists', ['id'], unique=False)
    op.alter_column('todo_notification_rules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_todo_notification_rules_id'), 'todo_notification_rules', ['id'], unique=False)
    op.drop_index('idx_todo_postpone_logs_date', table_name='todo_postpone_logs')
    op.create_index(op.f('ix_todo_postpone_logs_id'), 'todo_postpone_logs', ['id'], unique=False)
    op.create_index('idx_transactions_category', 'transactions', ['category'], unique=False)
    op.create_index('idx_transactions_date', 'transactions', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index('idx_user_api_keys_user', 'user_api_keys', ['user_id'], unique=False)
    op.create_index('idx_user_api_keys_user_provider', 'user_api_keys', ['user_id', 'provider'], unique=True)
    op.create_index(op.f('ix_user_api_keys_id'), 'user_api_keys', ['id'], unique=False)
    op.create_index(op.f('ix_user_body_profiles_id'), 'user_body_profiles', ['id'], unique=False)
    op.create_index('idx_user_budget_settings_budget', 'user_budget_settings', ['budget_settings_id'], unique=False)
    op.create_index('idx_user_budget_settings_user', 'user_budget_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_budget_settings_id'), 'user_budget_settings', ['id'], unique=False)
    op.create_index('idx_user_categories_category', 'user_categories', ['category_id'], unique=False)
    op.create_index('idx_user_categories_user', 'user_categories', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_categories_id'), 'user_categories', ['id'], unique=False)
    op.create_index('idx_user_receipts_receipt', 'user_receipts', ['receipt_id'], unique=False)
    op.create_index('idx_user_receipts_user', 'user_receipts', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_receipts_id'), 'user_receipts', ['id'], unique=False)
    op.create_index('idx_user_transactions_transaction', 'user_transactions', ['transaction_id'], unique=False)
    op.create_index('idx_user_transactions_user', 'user_transactions', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_transactions_id'), 'user_transactions', ['id'], unique=False)
    op.create_index('idx_users_email_hash', 'users', ['email_hash'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index('idx_vouchers_code', 'vouchers', ['code'], unique=False)
    op.create_index('idx_vouchers_used_by', 'vouchers', ['used_by_user_id'], unique=False)
    op.create_index(op.f('ix_vouchers_id'), 'vouchers', ['id'], unique=False)
    op.create_index('idx_weight_entries_date', 'weight_entries', ['date'], unique=False)
    op.create_index('idx_weight_entries_user', 'weight_entries', ['user_id'], unique=False)
    op.create_index(op.f('ix_weight_entries_id'), 'weight_entries', ['id'], unique=False)
    op.alter_column('workouts', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.create_index('idx_workouts_date', 'workouts', ['date'], unique=False)
    op.create_index('idx_workouts_user', 'workouts', ['user_id'], unique=False)
    op.create_index(op.f('ix_workouts_id'), 'workouts', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workouts_id'), table_name='workouts')
    op.drop_index('idx_workouts_user', table_name='workouts')
    op.drop_index('idx_workouts_date', table_name='workouts')
    op.alter_column('workouts', 'total_paused_seconds',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_weight_entries_id'), table_name='weight_entries')
    op.drop_index('idx_weight_entries_user', table_name='weight_entries')
    op.drop_index('idx_weight_entries_date', table_name='weight_entries')
    op.drop_index(op.f('ix_vouchers_id'), table_name='vouchers')
    op.drop_index('idx_vouchers_used_by', table_name='vouchers')
    op.drop_index('idx_vouchers_code', table_name='vouchers')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index('idx_users_email_hash', table_name='users')
    op.drop_index(op.f('ix_user_transactions_id'), table_name='user_transactions')
    op.drop_index('idx_user_transactions_user', table_name='user_transactions')
    op.drop_index('idx_user_transactions_transaction', table_name='user_transactions')
    op.drop_index(op.f('ix_user_receipts_id'), table_name='user_receipts')
    op.drop_index('idx_user_receipts_user', table_name='user_receipts')
    op.drop_index('idx_user_receipts_receipt', table_name='user_receipts')
    op.drop_index(op.f('ix_user_categories_id'), table_name='user_categories')
    op.drop_index('idx_user_categories_user', table_name='user_categories')
    op.drop_index('idx_user_categories_category', table_name='user_categories')
    op.drop_index(op.f('ix_user_budget_settings_id'), table_name='user_budget_settings')
    op.drop_index('idx_user_budget_settings_user', table_name='user_budget_settings')
    op.drop_index('idx_user_budget_settings_budget', table_name='user_budget_settings')
    op.drop_index(op.f('ix_user_body_profiles_id'), table_name='user_body_profiles')
    op.drop_index(op.f('ix_user_api_keys_id'), table_name='user_api_keys')
    op.drop_index('idx_user_api_keys_user_provider', table_name='user_api_keys')
    op.drop_index('idx_user_api_keys_user', table_name='user_api_keys')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index('idx_transactions_date', table_name='transactions')
    op.drop_index('idx_transactions_category', table_name='transactions')
    op.drop_index(op.f('ix_todo_postpone_logs_id'), table_name='todo_postpone_logs')
    op.create_index('idx_todo_postpone_logs_date', 'todo_postpone_logs', ['postponed_at'], unique=False)
    op.drop_index(op.f('ix_todo_notification_rules_id'), table_name='todo_notification_rules')
    op.alter_column('todo_notification_rules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_todo_lists_id'), table_name='todo_lists')
    op.alter_column('todo_lists', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_todo_items_id'), table_name='todo_items')
    op.alter_column('todo_items', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_shopping_lists_id'), table_name='shopping_lists')
    op.alter_column('shopping_lists', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_shopping_list_items_id'), table_name='shopping_list_items')
    op.alter_column('shopping_list_items', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index('idx_receipts_scan_date', table_name='receipts')
    op.drop_index('idx_receipts_merchant', table_name='receipts')
    op.drop_index('idx_receipts_category', table_name='receipts')
    op.alter_column('notification_schedules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_monthly_imports_id'), table_name='monthly_imports')
    op.drop_index('idx_monthly_imports_month', table_name='monthly_imports')
    op.drop_index(op.f('ix_meditation_sessions_id'), table_name='meditation_sessions')
    op.alter_column('meditation_sessions', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('meditation_sessions', 'completed',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_medicines_id'), table_name='medicines')
    op.alter_column('medicines', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_medicine_schedules_id'), table_name='medicine_schedules')
    op.alter_column('medicine_schedules', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_medicine_logs_id'), table_name='medicine_logs')
    op.alter_column('medicine_logs', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_journal_reports_id'), table_name='journal_reports')
    op.alter_column('journal_reports', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_journal_items_id'), table_name='journal_items')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_date'), table_name='journal_entries')
    op.alter_column('journal_entries', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_households_id'), table_name='households')
    op.drop_index('idx_households_uid', table_name='households')
    op.drop_index(op.f('ix_household_transactions_id'), table_name='household_transactions')
    op.drop_index('idx_household_transactions_transaction', table_name='household_transactions')
    op.drop_index('idx_household_transactions_household', table_name='household_transactions')
    op.drop_index(op.f('ix_household_receipts_id'), table_name='household_receipts')
    op.drop_index('idx_household_receipts_receipt', table_name='household_receipts')
    op.drop_index('idx_household_receipts_household', table_name='household_receipts')
    op.drop_index(op.f('ix_household_members_id'), table_name='household_members')
    op.drop_index('idx_household_members_user', table_name='household_members')
    op.drop_index('idx_household_members_household', table_name='household_members')
    op.drop_index(op.f('ix_household_invitations_id'), table_name='household_invitations')
    op.drop_index('idx_household_invitations_token', table_name='household_invitations')
    op.drop_index('idx_household_invitations_household', table_name='household_invitations')
    op.drop_index(op.f('ix_household_categories_id'), table_name='household_categories')
    op.drop_index('idx_household_categories_household', table_name='household_categories')
    op.drop_index('idx_household_categories_category', table_name='household_categories')
    op.drop_index(op.f('ix_household_budget_settings_id'), table_name='household_budget_settings')
    op.drop_index('idx_household_budget_settings_household', table_name='household_budget_settings')
    op.drop_index('idx_household_budget_settings_budget', table_name='household_budget_settings')
    op.drop_index(op.f('ix_food_reminder_settings_id'), table_name='food_reminder_settings')
    op.drop_index(op.f('ix_food_products_id'), table_name='food_products')
    op.drop_index('idx_food_products_name_normalized', table_name='food_products')
    op.drop_index('idx_food_products_category', table_name='food_products')
    op.drop_index('idx_food_products_barcode', table_name='food_products')
    op.drop_index(op.f('ix_food_product_aliases_id'), table_name='food_product_aliases')
    op.drop_index('idx_food_product_aliases_product', table_name='food_product_aliases')
    op.drop_index('idx_food_product_aliases_normalized', table_name='food_product_aliases')
    op.drop_index(op.f('ix_food_pending_imports_id'), table_name='food_pending_imports')
    op.drop_index('idx_food_pending_imports_user', table_name='food_pending_imports')
    op.drop_index('idx_food_pending_imports_status', table_name='food_pending_imports')
    op.drop_index('idx_food_pending_imports_receipt', table_name='food_pending_imports')
    op.drop_index('idx_food_pending_imports_household', table_name='food_pending_imports')
    op.drop_index(op.f('ix_food_pending_import_items_id'), table_name='food_pending_import_items')
    op.drop_index('idx_food_pending_import_items_status', table_name='food_pending_import_items')
    op.drop_index('idx_food_pending_import_items_import', table_name='food_pending_import_items')
    op.drop_index(op.f('ix_food_inventory_id'), table_name='food_inventory')
    op.drop_index('idx_food_inventory_user', table_name='food_inventory')
    op.drop_index('idx_food_inventory_status', table_name='food_inventory')
    op.drop_index('idx_food_inventory_product', table_name='food_inventory')
    op.drop_index('idx_food_inventory_location', table_name='food_inventory')
    op.drop_index('idx_food_inventory_household', table_name='food_inventory')
    op.drop_index('idx_food_inventory_expiry', table_name='food_inventory')
    op.drop_index(op.f('ix_food_expiry_reminders_id'), table_name='food_expiry_reminders')
    op.drop_index('idx_food_expiry_reminders_user', table_name='food_expiry_reminders')
    op.drop_index('idx_food_expiry_reminders_status', table_name='food_expiry_reminders')
    op.drop_index('idx_food_expiry_reminders_inventory', table_name='food_expiry_reminders')
    op.drop_index(op.f('ix_food_consumption_log_id'), table_name='food_consumption_log')
    op.drop_index('idx_food_consumption_log_user', table_name='food_consumption_log')
    op.drop_index('idx_food_consumption_log_consumed_at', table_name='food_consumption_log')
    op.drop_index(op.f('ix_food_categories_id'), table_name='food_categories')
    op.drop_index('idx_food_categories_name', table_name='food_categories')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index('idx_exercises_workout', table_name='exercises')
    op.drop_index(op.f('ix_exercise_sets_id'), table_name='exercise_sets')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_categories_name', table_name='categories')
    op.drop_index(op.f('ix_budget_settings_id'), table_name='budget_settings')
    op.drop_index(op.f('ix_body_measurement_entries_id'), table_name='body_measurement_entries')
    op.alter_column('body_measurement_entries', 'created_at',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_oauth_authorization_codes_id'), table_name='oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_authorization_codes_code'), table_name='oauth_authorization_codes')
    op.drop_index('idx_oauth_codes_code', table_name='oauth_authorization_codes')
    op.drop_index('idx_oauth_codes_client', table_name='oauth_authorization_codes')
    op.drop_table('oauth_authorization_codes')
    op.drop_index(op.f('ix_oauth_access_tokens_refresh_token'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_id'), table_name='oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_access_tokens_access_token'), table_name='oauth_access_tokens')
    op.drop_index('idx_oauth_tokens_user', table_name='oauth_access_tokens')
    op.drop_index('idx_oauth_tokens_refresh', table_name='oauth_access_tokens')
    op.drop_index('idx_oauth_tokens_access', table_name='oauth_access_tokens')
    op.drop_table('oauth_access_tokens')
    op.drop_index(op.f('ix_oauth_clients_id'), table_name='oauth_clients')
    op.drop_index(op.f('ix_oauth_clients_client_id'), table_name='oauth_clients')
    op.drop_index('idx_oauth_clients_client_id', table_name='oauth_clients')
    op.drop_table('oauth_clients')
    # ### end Alembic commands ###
